alias cdcustom='cd ~/.oh-my-zsh/custom'
alias cdrepo='cd ~/repos/'
alias flushdns='sudo killall -HUP mDNSResponder'
alias tf='terraform'
alias tfi="terraform init"
alias tfa="terraform apply"
alias tfcreds="/Users/calvin/repos/tfcreds/run.sh"
alias htop="sudo htop"
alias vim="nvim"
