alias cdcustom="cd ~/.oh-my-zsh/custom"
alias cdrepo="cd ~/repos/"
alias ops="cd ~/repos/ap3-ops"
alias api="cd ~/repos/ap3-api"
alias ui="cd ~/repos/ap3-ui"
alias flushdns="sudo killall -HUP mDNSResponder"
alias tf="terraform"
alias tfi="terraform init; terraform providers lock -platform=linux_amd64 -platform=darwin_amd64 -platform=darwin_arm64;"
alias tfiu="terraform init --upgrade; terraform providers lock -platform=linux_amd64 -platform=darwin_amd64 -platform=darwin_arm64;"
alias tfa="terraform apply"
alias tfcreds="/Users/calvin/repos/ap3-ops/tfcreds/run.sh"
alias htop="sudo htop"
alias vim="nvim"
