POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(virtualenv vcs dir root_indicator dir_writable status)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="╰─❯ "
POWERLEVEL9K_PYTHON_ICON='\UE73C'
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR="\uE0B4"
