- defaults:
    link:
      create: true
      force: true
- clean: ['~']

# dotfiles
# indent 4 spaces for a valid dict in list
- link:
    ~/.atom/:
      path: atom/*
      glob: true
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    ~/.nanorc: nano/nanorc
    ~/.ssh/config: ssh/config
    ~/.vimrc: vim/vimrc
    ~/.vim/bundle: vim/bundle
    ~/.zshrc: zsh/zshrc
    ~/.oh-my-zsh/custom: zsh/custom
    ~/.mackup.cfg: mac/mackup.cfg

- shell:
  - description: oh-my-zsh
    command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    stdout: true
  - description: install homebrew
    command: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    stdout: true
  - description: install homebrew formulas
    command: bash -c "cd mac && brew bundle"
    stdout: true
  - description: install pip modules
    command: bash -c "pip install -r pip/requirements.txt"
    stdout: true
  - description: install npm packages
    command: bash -c "< npm/packages.txt xargs npm install -g"
    stdout: true
  - description: install nano themes
    command: git-clone-idempotent git@github.com:scopatz/nanorc.git ~/.nano
    stdout: true
  - description: restore mackup backup
    command: bash -c "cd mac && ./mackup-restore.sh"
    stdout: true
  - description: install atom packages
    command: apm install --packages-file ~/.atom/package-list.txt
    stdout: true
  - description: restore & app system preferences
    command: bash -c "cd mac && ./defaults-restore.sh"
    stdout: true
