- defaults:
    link:
      create: true
      force: true
- clean: ['~']

- shell:
  # oh-my-zsh
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  # homebrew
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - cd mac && brew bundle
  # pip
  - pip install -r pip/requirements.txt
  # npm
  - < npm/packages.txt xargs npm install -g
  # Nano
  - git-clone-idempotent git@github.com:scopatz/nanorc.git ~/.nano
  # VIM
  - git-clone-idempotent https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  - vim +PluginInstall +qall

# dotfiles
# indent 4 spaces for a valid dict in list
- link:
    ~/.atom/:
      path: atom/*
      glob: true
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    ~/.nanorc: nano/nanorc
    ~/.ssh/config: ssh/config
    ~/.vimrc: vim/vimrc
    ~/.zshrc: zsh/zshrc
    ~/.oh-my-zsh/custom: zsh/custom
    ~/.mackup.cfg: mac/mackup.cfg

