---

- defaults:
    link:
      create: true
      force: true
- clean: ['~']

# both
- link:
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global

    ~/.ssh/config: ssh/config

    ~/.config/nvim/init.vim: vim/init.vim
    ~/.vim/bundle: vim/bundle
    ~/.local/share/nvim/site/autoload: vim/autoload

    ~/.pylintrc: python/pylintrc

    ~/.terraformrc: terraform/terraformrc

# linux
- defaults:
    link:
      if: '[ "$(uname -s)" = "Linux" ]'
- link:
    ~/.gitlocal:
      path: git/linux

# mac
- defaults:
    link:
      if: '[ "$(uname -s)" = "Darwin" ]'
- link:
    ~/.atom/:
      path: atom/*
      glob: true
    ~/.gitlocal:
      path: git/mac
    ~/Library/KeyBindings/DefaultKeyBinding.dict:
      path: mac/DefaultKeyBindings.dict

- shell:
  -
    description: apt-get install
    command: |
      if [ "$(uname -s)" = "Linux" ]; then
        sudo apt-get update
        sudo apt-get install -y $(cat apt/packages.txt)

        . apt/neovim.sh
        . apt/nodejs.sh

      fi
    stdout: true
    stdin: true
  -
    description: oh-my-zsh
    command: |
      if [ -d ~/.oh-my-zsh ]; then
        if [ ! -d ~/.oh-my-zsh/.git ]; then
          rm -rf ~/.oh-my-zsh
        fi
      fi

      sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || :
    stdout: true
    stdin: true
  -
    description: install homebrew
    command: |
      if [ "$(uname -s)" = "Darwin" ]; then
        if ! command -v brew &> /dev/null; then
          /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        fi
      fi
    stdout: true
    stdin: true
  -
    description: install homebrew formulas
    command: |
      if [ "$(uname -s)" = "Darwin" ]; then
        bash -c "cd mac && brew bundle --no-upgrade --no-lock"
      fi
    stdout: true
    stdin: true
  -
    description: install pip3 modules
    command: bash -c "pip3 install -r python/pip3-requirements.txt"
    stdout: true
    stdin: true
  -
    description: install npm packages
    command: |
      if [ "$(uname -s)" = "Darwin" ]; then
        bash -c "< npm/packages.txt xargs npm install -g"
      elif [ "$(uname -s)" = "Linux" ]; then
        bash -c "< npm/packages.txt xargs sudo npm install -g"
      fi
    stdout: true
    stdin: true
  -
    description: install atom packages
    command: |
      if [ "$(uname -s)" = "Darwin" ]; then
        echo "Getting installed Atom packages"
        installed=$(apm list -i -b -no-color)

        echo "Installing missing Atom packages"
        while read -r p; do
          echo "Checking if $p is installed..."
          if ! echo "$installed" | grep --silent "$p"; then
            echo "Installing ${p}..."
            apm install --production "$p"
          fi
        done < atom/package-list.txt
      fi
    stdout: true
    stdin: true
  -
    description: disable last login on new terminal session
    command: |
      if [ "$(uname -s)" = "Darwin" ]; then
        touch ~/.hushlogin
      fi
    stdout: true
    stdin: true
  -
    description: stop .DS_Store files on network drives
    command: |
      if [ "$(uname -s)" = "Darwin" ]; then
        defaults write com.apple.desktopservices DSDontWriteNetworkStores true
      fi
    stdout: true
    stdin: true
  -
    description: Disable keyboard accents popup / enable key repeat
    command: |
      if [ "$(uname -s)" = "Darwin" ]; then
        defaults write -g ApplePressAndHoldEnabled -bool false
      fi
    stdout: true
    stdin: true
  -
    description: Install MesloLGS NF fonts
    command:
      if [ "$(uname -s)" = "Darwin" ]; then
        cp fonts/* ~/Library/Fonts
      fi
    stdout: true
    stdin: true

# can't clone repo if already exists
- link:
    ~/.zshrc: zsh/zshrc
    ~/.p10k: zsh/p10k.zsh
    ~/.oh-my-zsh/custom/:
      glob: true
      path: zsh/custom/*.zsh
    ~/.oh-my-zsh/custom/plugins/:
      glob: true
      path: zsh/custom/plugins/*
    ~/.oh-my-zsh/custom/themes/:
      glob: true
      path: zsh/custom/themes/*

# remove dead symlinks
- clean:
    - ~/.oh-my-zsh/custom
    - ~/.oh-my-zsh/custom/plugins/
    - ~/.oh-my-zsh/custom/themes/
