- defaults:
    link:
      create: true
      force: true
- clean: ['~']

# dotfiles
- link:
    ~/.atom/:
      path: atom/*
      glob: true
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    ~/.nanorc: nano/nanorc
    ~/.ssh/config: ssh/config
    ~/.config/nvim/init.vim: vim/init.vim
    ~/.vim/bundle: vim/bundle
    ~/.local/share/nvim/site/autoload: vim/autoload

- shell:
  -
    description: oh-my-zsh
    command: |
      if [ -d ~/.oh-my-zsh ]; then
        if [ ! -d ~/.oh-my-zsh/.git ]; then
          rm -rf ~/.oh-my-zsh
        fi
      fi

      sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || :
    stdout: true
    stdin: true
    command: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  -
    description: install homebrew
    stdout: true
    stdin: true
  -
    description: install homebrew formulas
    command: bash -c "cd mac && brew bundle"
    stdout: true
    stdin: true
  -
    description: install pip3 modules
    command: bash -c "pip3 install -r pip/pip3-requirements.txt"
    stdout: true
    stdin: true
  -
    description: install npm packages
    command: bash -c "< npm/packages.txt xargs npm install -g"
    stdout: true
    stdin: true
  -
    description: install nano themes
    command: git-clone-idempotent https://github.com/scopatz/nanorc.git ~/.nano
    stdout: true
    stdin: true
    command: apm install --production --packages-file atom/package-list.txt
  -
    description: install atom packages
    stdout: true
    stdin: true
  -
    description: disable last login on new terminal session
    command: touch ~/.hushlogin
    stdout: true
    stdin: true

# can't clone repo if already exists
- link:
    ~/.zshrc: zsh/zshrc
    ~/.oh-my-zsh/custom/:
      glob: true
      path: zsh/custom/*.zsh
    ~/.oh-my-zsh/custom/plugins/:
      glob: true
      path: zsh/custom/plugins/*
    ~/.oh-my-zsh/custom/themes/:
      glob: true
      path: zsh/custom/themes/*
