# indent 4 spaces for a valid dict in list

- defaults:
    link:
      create: true

- clean: ['~']

- link:
    # dotfiles
    ~/.bash_rc:
      path: bash/bash_rc
    ~/.bash_profile:
      path: bash/bash_profile
    ~/.gitconfig:
      path: git/gitconfig
    ~/.ssh/config:
      path: ssh/config
    ~/.vimrc:
      path: vim/vimrc
    ~/.zshrc:
      path: zsh/zshrc
    ~/.oh-my-zsh/custom:
      path: zsh/custom

- shell:
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  - pip install pip/requirements.txt
  - < npm/packages.txt xargs npm install -g
  - cd mac && brew bundle