k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: true
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: ap3-prod-eks
  currentCluster: arn:aws:eks:us-east-2:409414527402:cluster/ap3-prod-eks
  clusters:
    arn:aws:eks:ap-southeast-2:409414527402:cluster/ap3-auprod-eks:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - ap3-prod-master
        - mongodb-exporter
        - linkerd-multicluster
        - ap3-auprod-master
        - cluster-overprovisioner
        - buildkite-agent
        - all
        - ap3-auprod-preprod
        - prometheus-operator
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:ap-southeast-2:601446024623:cluster/ap3-stg-eks:
      namespace:
        active: ap3-stg-master
        lockFavorites: false
        favorites:
        - frp
        - ap3-stg-qa
        - ap3-stg-master
        - velero
        - mysql-proxy
        - talk-ai
        - ap2-stg-master
        - linkerd
        - linkerd-multicluster
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:eu-central-1:409414527402:cluster/ap3-euprod-eks:
      namespace:
        active: ap3-euprod-preprod
        lockFavorites: false
        favorites:
        - linkerd-multicluster
        - linkerd-viz
        - mongo-backups
        - ap3-euprod-preprod
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:022761819571:cluster/ops-shared-eks:
      namespace:
        active: ap3-stg-master
        lockFavorites: false
        favorites:
        - linkerd
        - all
        - ap3-stg-master
        - falco
        - default
        - karpenter
        - athens-proxy
        - ap3-application-logs
        - aws-fsx-csi-driver
      view:
        active: svc
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:409414527402:cluster/ap3-prod-eks:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - elasticsearch-exporter
        - kube-system
        - mongodb-exporter
        - linkerd-viz
        - ap3-prod-preprod
        - buildkite-agent
        - s3-backups-checker
        - mongo-backups
        - ap3-prod-master
      view:
        active: "no"
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/_t/fxhbmswn7yj755h6t61x7p4h0000gn/T/k9s-screens-calvin
