k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: ap3-prod-eks
  currentCluster: arn:aws:eks:us-east-2:409414527402:cluster/ap3-prod-eks
  clusters:
    arn:aws:eks:ap-southeast-2:409414527402:cluster/ap3-auprod-eks:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - karpenter
        - buildkite-agent
        - prometheus-operator
        - filebeat
        - all
        - ap3-auprod-master
        - default
      view:
        active: "no"
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:ap-southeast-2:601446024623:cluster/ap3-stg-eks:
      namespace:
        active: ap3-stg-master
        lockFavorites: false
        favorites:
        - karpenter
        - buildkite-agent
        - kube-system
        - nats-exporter
        - ap3-stg-master
        - cluster-overprovisioner
        - prometheus-operator
        - ap3-stg-capture-api-cname-proxy
        - all
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:eu-central-1:409414527402:cluster/ap3-euprod-eks:
      namespace:
        active: ap3-euprod-master
        lockFavorites: false
        favorites:
        - kube-system
        - s3-backups-checker
        - anchore-scanner
        - all
        - ap3-euprod-preprod
        - ap3-euprod-master
        - default
      view:
        active: "no"
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:022761819571:cluster/ops-shared-eks:
      namespace:
        active: trivy-system
        lockFavorites: false
        favorites:
        - antora
        - cert-manager
        - es-watcher-exporter
        - trivy-system
        - all
        - buildkite-agent
        - s3-backups-checker
        - postgres-exporter
        - anchore-scanner
      view:
        active: job
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:409414527402:cluster/ap3-prod-eks:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - cluster-overprovisioner
        - elasticsearch-exporter
        - ap3-prod-capture-api-cname-proxy
        - filebeat
        - s3-backups-checker
        - all
        - ap3-prod-preprod
        - ap3-prod-master
        - default
      view:
        active: pdb
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    gke_ap3-prod_us-central1_ap3-cluster-prod:
      namespace:
        active: prometheus-operator
        lockFavorites: false
        favorites:
        - external-dns
        - gtoken-webhook
        - ap3-prod-master
        - prometheus-operator
        - all
        - filebeat
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/_t/fxhbmswn7yj755h6t61x7p4h0000gn/T/k9s-screens-calvin
