k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  enableImageScan: false
  headless: false
  logoless: true
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: ap3-stg-eks
  currentCluster: arn:aws:eks:ap-southeast-2:601446024623:cluster/ap3-stg-eks
  keepMissingClusters: false
  clusters:
    arn:aws:eks:ap-southeast-2:409414527402:cluster/ap3-auprod-eks:
      namespace:
        active: ap3-auprod-preprod
        lockFavorites: false
        favorites:
        - ap3-auprod-preprod
        - ap3-auprod-master
        - ingress-nginx
        - falco
        - all
        - kube-system
        - buildkite-agent
        - prometheus-operator
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    arn:aws:eks:ap-southeast-2:601446024623:cluster/ap3-stg-eks:
      namespace:
        active: ap3-stg-master
        lockFavorites: false
        favorites:
        - talk-ai
        - knowledge-base-cname-proxy
        - ap3-stg-capture-api-cname-proxy
        - cluster-overprovisioner
        - ingress-nginx
        - all
        - ap3-stg-master
        - aws-load-balancer-controller
        - kube-system
      view:
        active: ing
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    arn:aws:eks:eu-central-1:409414527402:cluster/ap3-euprod-eks:
      namespace:
        active: ap3-euprod-master
        lockFavorites: false
        favorites:
        - ap3-euprod-master
        - aws-load-balancer-controller
        - ingress-nginx
        - buildkite-agent
        - all
        - mongodb-exporter
        - prometheus-operator
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:022761819571:cluster/ops-shared-eks:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - buildkite-agent
        - kube-system
        - mysql-proxy
        - mysqld-exporter
        - linkerd
        - all
        - prometheus-operator
        - oncall
        - athens-proxy
      view:
        active: pod
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:409414527402:cluster/ap3-prod-eks:
      namespace:
        active: ap3-prod-master
        lockFavorites: false
        favorites:
        - ingress-nginx
        - kube-system
        - mongo-backups
        - ap3-prod-master
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:808259360302:cluster/ap2-stg-eks:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - aws-load-balancer-controller
        - ingress-nginx
        - all
        - default
      view:
        active: dp
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:914129350720:cluster/ap2-prod-eks:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - kube-system
        - external-dns
        - aws-load-balancer-controller
        - ap2-prod-master
        - buildkite-agent
        - loki
        - all
        - prometheus-operator
      view:
        active: ns
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/_t/fxhbmswn7yj755h6t61x7p4h0000gn/T/k9s-screens-calvin
  disablePodCounting: false
