k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: ap3-stg-eks
  currentCluster: arn:aws:eks:ap-southeast-2:601446024623:cluster/ap3-stg-eks
  clusters:
    arn:aws:eks:ap-southeast-2:409414527402:cluster/ap3-auprod-eks:
      namespace:
        active: ap3-auprod-master
        lockFavorites: false
        favorites:
        - ap3-auprod-master
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:ap-southeast-2:601446024623:cluster/ap3-stg-eks:
      namespace:
        active: ap3-stg-master
        lockFavorites: false
        favorites:
        - ap2-stg-master
        - linkerd-viz
        - linkerd-smi
        - linkerd
        - ap3-stg-master
        - blackbox-exporter
        - prometheus-operator
        - ingress-nginx
        - nats-exporter
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:eu-central-1:409414527402:cluster/ap3-euprod-eks:
      namespace:
        active: ap3-euprod-preprod
        lockFavorites: false
        favorites:
        - ap3-euprod-preprod
        - ap3-euprod-master
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:022761819571:cluster/ops-shared-eks:
      namespace:
        active: antora
        lockFavorites: false
        favorites:
        - external-dns
        - buildkite-artifacts-s3-proxy
        - elasticsearch-exporter
        - kube-system
        - falco
        - all
        - athens-proxy
        - loki
        - antora
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:409414527402:cluster/ap3-prod-eks:
      namespace:
        active: ap3-prod-master
        lockFavorites: false
        favorites:
        - s3-backups-checker
        - all
        - ap3-prod-preprod
        - ap3-prod-master
        - default
      view:
        active: job
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_ap3-prod_us-central1_ap3-cluster-prod:
      namespace:
        active: gtoken-webhook
        lockFavorites: false
        favorites:
        - gtoken-webhook
        - ap3-prod-master
        - prometheus-operator
        - all
        - filebeat
        - default
      view:
        active: mutatingwebhookconfiguration
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/_t/fxhbmswn7yj755h6t61x7p4h0000gn/T/k9s-screens-calvin
