k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: ap2-stg-eks
  currentCluster: arn:aws:eks:us-east-2:808259360302:cluster/ap2-stg-eks
  clusters:
    arn:aws:eks:ap-southeast-2:409414527402:cluster/ap3-auprod-eks:
      namespace:
        active: ap3-prod-master
        lockFavorites: false
        favorites:
        - external-dns
        - ap3-prod-master
        - default
      view:
        active: "no"
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:ap-southeast-2:601446024623:cluster/ap3-stg-eks:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - ap3-stg-qa
        - prometheus-operator
        - buildkite-agent
        - kube-system
        - linkerd-multicluster
        - all
        - ap3-stg-master
        - default
      view:
        active: ds
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:eu-central-1:409414527402:cluster/ap3-euprod-eks:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - prometheus-operator
        - all
        - kube-system
        - ap3-euprod-preprod
        - default
      view:
        active: sts
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:022761819571:cluster/ops-shared-eks:
      namespace:
        active: prometheus-operator
        lockFavorites: false
        favorites:
        - prometheus-operator
        - terraform-cloud-operator
        - oncall
        - default
        - karpenter
        - grafana
        - cluster-proportional-autoscaler
        - all
        - buildkite-agent
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:409414527402:cluster/ap3-prod-eks:
      namespace:
        active: prometheus-operator
        lockFavorites: false
        favorites:
        - prometheus-operator
        - cluster-overprovisioner
        - all
        - linkerd-multicluster
        - ap3-prod-master
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:808259360302:cluster/ap2-stg-eks:
      namespace:
        active: ap2-stg-master
        lockFavorites: false
        favorites:
        - ap2-stg-master
        - all
        - kube-system
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/_t/fxhbmswn7yj755h6t61x7p4h0000gn/T/k9s-screens-calvin
