k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  enableImageScan: false
  headless: false
  logoless: true
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: ap3-stg-eks
  currentCluster: arn:aws:eks:ap-southeast-2:601446024623:cluster/ap3-stg-eks
  keepMissingClusters: false
  clusters:
    arn:aws:eks:ap-southeast-2:409414527402:cluster/ap3-auprod-eks:
      namespace:
        active: prometheus-operator
        lockFavorites: false
        favorites:
        - prometheus-operator
        - default
      view:
        active: "no"
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    arn:aws:eks:ap-southeast-2:601446024623:cluster/ap3-stg-eks:
      namespace:
        active: ap3-stg-master
        lockFavorites: false
        favorites:
        - mysql-proxy
        - prometheus-operator
        - athens-proxy
        - buildkite-agent
        - clamav
        - linkerd-multicluster
        - all
        - ap3-stg-master
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    arn:aws:eks:eu-central-1:409414527402:cluster/ap3-euprod-eks:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - mongodb-exporter
        - prometheus-operator
        - default
      view:
        active: servicemonitor
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:022761819571:cluster/ops-shared-eks:
      namespace:
        active: mysql-proxy
        lockFavorites: false
        favorites:
        - mysql-proxy
        - mysqld-exporter
        - linkerd
        - all
        - prometheus-operator
        - oncall
        - athens-proxy
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:409414527402:cluster/ap3-prod-eks:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - mongo-backups
        - karpenter
        - ap3-prod-master
        - default
      view:
        active: cj
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:808259360302:cluster/ap2-stg-eks:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/_t/fxhbmswn7yj755h6t61x7p4h0000gn/T/k9s-screens-calvin
  disablePodCounting: false
