{
    DefaultsSanitizedVersion = 20180510;
    DeviceCountryCode = AU;
    GEOLastNetworkDefaultsETag = "\\"9d1-583891516f238\\"";
    GEOLastNetworkDefaultsURL = "https://configuration.apple.com/configurations/pep/config/geo/networkDefaults-osx-10.14.4.plist";
    GEOLastResourceManifestURL = "https://gspe35-ssl.ls.apple.com/geo_manifest/dynamic/config?application=geod&application_version=1&country_code=AU&hardware=MacBookPro15,2&os=osx&os_build=18E226&os_version=10.14.4";
    LogMessageUsageXPCActivityTriggerCount = 0;
    kOldestLogMessageTimeDefaultsKeyUsage = "2019-04-24 02:01:52 +0000";
}
