{
    DC =     {
        AVConnector =         {
            v1 =             (
                8,
                                {
                    accounts =                     (
                        8,
                                                {
                            def =                             (
                                8,
                                                                {
                                }
                            );
                        }
                    );
                    connectors =                     (
                        8,
                                                {
                            en0us =                             (
                                8,
                                                                {
                                }
                            );
                        }
                    );
                    order =                     (
                        8,
                                                {
                            en0us =                             (
                                8,
                                                                {
                                    "order_for_add" =                                     (
                                        8,
                                                                                {
                                            0 =                                             (
                                                8,
                                                                                                {
                                                    "section_key" =                                                     (
                                                        4,
                                                        <61646f62 655f746f 6f6c7300>
                                                    );
                                                    "section_label" =                                                     (
                                                        5,
                                                        "Featured Storage"
                                                    );
                                                    "section_order" =                                                     (
                                                        8,
                                                                                                                {
                                                            0 =                                                             (
                                                                8,
                                                                                                                                {
                                                                    alwaysAppear =                                                                     (
                                                                        0,
                                                                        0
                                                                    );
                                                                    name =                                                                     (
                                                                        4,
                                                                        <626f7800>
                                                                    );
                                                                }
                                                            );
                                                            1 =                                                             (
                                                                8,
                                                                                                                                {
                                                                    alwaysAppear =                                                                     (
                                                                        0,
                                                                        0
                                                                    );
                                                                    name =                                                                     (
                                                                        4,
                                                                        <64726f70 626f7800>
                                                                    );
                                                                }
                                                            );
                                                            2 =                                                             (
                                                                8,
                                                                                                                                {
                                                                    alwaysAppear =                                                                     (
                                                                        0,
                                                                        0
                                                                    );
                                                                    name =                                                                     (
                                                                        4,
                                                                        <676f6f67 6c654472 69766500>
                                                                    );
                                                                }
                                                            );
                                                            3 =                                                             (
                                                                8,
                                                                                                                                {
                                                                    alwaysAppear =                                                                     (
                                                                        0,
                                                                        0
                                                                    );
                                                                    name =                                                                     (
                                                                        4,
                                                                        <6f6e6564 72697665 00>
                                                                    );
                                                                }
                                                            );
                                                            4 =                                                             (
                                                                8,
                                                                                                                                {
                                                                    alwaysAppear =                                                                     (
                                                                        0,
                                                                        0
                                                                    );
                                                                    name =                                                                     (
                                                                        4,
                                                                        <6f6e6564 72697665 62757369 6e657373 00>
                                                                    );
                                                                }
                                                            );
                                                            5 =                                                             (
                                                                8,
                                                                                                                                {
                                                                    alwaysAppear =                                                                     (
                                                                        0,
                                                                        0
                                                                    );
                                                                    name =                                                                     (
                                                                        4,
                                                                        <6465736b 746f705f 73686172 65706f69 6e7400>
                                                                    );
                                                                }
                                                            );
                                                        }
                                                    );
                                                }
                                            );
                                        }
                                    );
                                    "order_for_file_sel_dlg" =                                     (
                                        8,
                                                                                {
                                            0 =                                             (
                                                8,
                                                                                                {
                                                    alwaysAppear =                                                     (
                                                        0,
                                                        0
                                                    );
                                                    name =                                                     (
                                                        4,
                                                        <626f7800>
                                                    );
                                                }
                                            );
                                            1 =                                             (
                                                8,
                                                                                                {
                                                    alwaysAppear =                                                     (
                                                        0,
                                                        0
                                                    );
                                                    name =                                                     (
                                                        4,
                                                        <64726f70 626f7800>
                                                    );
                                                }
                                            );
                                            2 =                                             (
                                                8,
                                                                                                {
                                                    alwaysAppear =                                                     (
                                                        0,
                                                        0
                                                    );
                                                    name =                                                     (
                                                        4,
                                                        <676f6f67 6c654472 69766500>
                                                    );
                                                }
                                            );
                                            3 =                                             (
                                                8,
                                                                                                {
                                                    alwaysAppear =                                                     (
                                                        0,
                                                        0
                                                    );
                                                    name =                                                     (
                                                        4,
                                                        <6f6e6564 72697665 00>
                                                    );
                                                }
                                            );
                                            4 =                                             (
                                                8,
                                                                                                {
                                                    alwaysAppear =                                                     (
                                                        0,
                                                        0
                                                    );
                                                    name =                                                     (
                                                        4,
                                                        <6f6e6564 72697665 62757369 6e657373 00>
                                                    );
                                                }
                                            );
                                            5 =                                             (
                                                8,
                                                                                                {
                                                    alwaysAppear =                                                     (
                                                        0,
                                                        0
                                                    );
                                                    name =                                                     (
                                                        4,
                                                        <6465736b 746f705f 73686172 65706f69 6e7400>
                                                    );
                                                }
                                            );
                                        }
                                    );
                                    "order_for_left_rail" =                                     (
                                        8,
                                                                                {
                                            0 =                                             (
                                                8,
                                                                                                {
                                                    alwaysAppear =                                                     (
                                                        0,
                                                        0
                                                    );
                                                    name =                                                     (
                                                        4,
                                                        <626f7800>
                                                    );
                                                }
                                            );
                                            1 =                                             (
                                                8,
                                                                                                {
                                                    alwaysAppear =                                                     (
                                                        0,
                                                        0
                                                    );
                                                    name =                                                     (
                                                        4,
                                                        <64726f70 626f7800>
                                                    );
                                                }
                                            );
                                            2 =                                             (
                                                8,
                                                                                                {
                                                    alwaysAppear =                                                     (
                                                        0,
                                                        0
                                                    );
                                                    name =                                                     (
                                                        4,
                                                        <676f6f67 6c654472 69766500>
                                                    );
                                                }
                                            );
                                            3 =                                             (
                                                8,
                                                                                                {
                                                    alwaysAppear =                                                     (
                                                        0,
                                                        0
                                                    );
                                                    name =                                                     (
                                                        4,
                                                        <6f6e6564 72697665 00>
                                                    );
                                                }
                                            );
                                            4 =                                             (
                                                8,
                                                                                                {
                                                    alwaysAppear =                                                     (
                                                        0,
                                                        0
                                                    );
                                                    name =                                                     (
                                                        4,
                                                        <6f6e6564 72697665 62757369 6e657373 00>
                                                    );
                                                }
                                            );
                                            5 =                                             (
                                                8,
                                                                                                {
                                                    alwaysAppear =                                                     (
                                                        0,
                                                        0
                                                    );
                                                    name =                                                     (
                                                        4,
                                                        <6465736b 746f705f 73686172 65706f69 6e7400>
                                                    );
                                                }
                                            );
                                        }
                                    );
                                }
                            );
                        }
                    );
                }
            );
        };
        AVConversionFromPDF =         {
            Settings =             (
                8,
                                {
                }
            );
        };
        AVConversionToPDF =         {
            Settings =             (
                8,
                                {
                }
            );
        };
        AVEntitlement =         {
            Activated =             (
                0,
                1
            );
            AppInitialized =             (
                0,
                1
            );
            EntitlementLevel =             (
                1,
                300
            );
            IsAMTLicensingCachedDate =             (
                4,
                <443a3230 31393034 32363033 32313534 2b313027 30302700>
            );
            IsSubscriptionLicensed =             (
                0,
                1
            );
            LastTrialNagShownDay =             (
                1,
                1034148
            );
            LicenseStatus =             (
                1,
                3
            );
            ProductGUID =             (
                4,
                <56377b7d 4163726f 62617443 6f6e742d 31322d4d 61632d47 4d00>
            );
            ProductName =             (
                4,
                <00>
            );
            ProductVersion =             (
                4,
                <302e3000>
            );
            SerialExpiryDate =             (
                1,
                0
            );
            Serialized =             (
                0,
                1
            );
            SynchronizeOPL =             (
                0,
                1
            );
        };
        AVGeneral =         {
            AddCustomFile =             (
                0,
                0
            );
            Dockables =             (
                8,
                                {
                    ExternalTabs =                     (
                        0,
                        0
                    );
                    InternalTabs =                     (
                        0,
                        0
                    );
                }
            );
            ForceQuitApp =             (
                0,
                0
            );
            HideUnreadHomeBannerMsgAtLaunch =             (
                0,
                1
            );
            MaxFrequentlyUsedTools =             (
                1,
                5
            );
            NumAcrobatLaunches =             (
                1,
                1
            );
            RecentFiles =             (
                8,
                                {
                    1 =                     (
                        8,
                                                {
                            DI =                             (
                                4,
                                <68747470 3a2f2f77 77772e61 646f6265 2e636f6d 2f676f2f 686f6d65 6163726f 72647275 6e696669 65643138 5f323031 3800>
                            );
                            DIText =                             (
                                5,
                                "http://www.adobe.com/go/homeacrordrunified18_2018"
                            );
                            Date =                             (
                                4,
                                <443a3230 31393034 32363033 32313534 2b313027 30302700>
                            );
                            FS =                             (
                                2,
                                <43485454 5000>
                            );
                            FileAncestors =                             (
                                4,
                                <5b5d00>
                            );
                            FileName =                             (
                                5,
                                "Welcome.pdf"
                            );
                        }
                    );
                }
            );
            RecentToolsList =             (
                8,
                                {
                }
            );
            ShowTaskButtonInfoBubble =             (
                0,
                0
            );
            TaskPanes =             (
                8,
                                {
                    BasicCommentPane =                     (
                        8,
                                                {
                            AllowMultipleExpandedPanels =                             (
                                0,
                                1
                            );
                        }
                    );
                }
            );
            Toolbars =             (
                8,
                                {
                    AdvCommenting =                     (
                        8,
                                                {
                        }
                    );
                    BasicCommenting =                     (
                        8,
                                                {
                        }
                    );
                    Commenting =                     (
                        8,
                                                {
                            Stamp =                             (
                                8,
                                                                {
                                    InternalExpanded =                                     (
                                        0,
                                        1
                                    );
                                }
                            );
                        }
                    );
                }
            );
            appFirstLaunchForNotifications =             (
                0,
                0
            );
            isFirstLaunch =             (
                0,
                0
            );
        };
        AVMeasuredFontSizes =         {
            10 =             (
                3,
                11
            );
            11 =             (
                3,
                "12.1"
            );
            13 =             (
                3,
                "14.2"
            );
            14 =             (
                3,
                "15.3"
            );
            15 =             (
                3,
                "16.4"
            );
            16 =             (
                3,
                "17.50000000000002"
            );
            18 =             (
                3,
                "19.70000000000002"
            );
        };
        AVTracker =         {
            LoadOnStart =             (
                0,
                0
            );
        };
        AcroApp =         {
            Favorites =             (
                8,
                                {
                    0 =                     (
                        2,
                        <43726561 74655044 46417070 00>
                    );
                    1 =                     (
                        2,
                        <436f6d62 696e6541 707000>
                    );
                    10 =                     (
                        2,
                        <50726f74 65637441 707000>
                    );
                    2 =                     (
                        2,
                        <45646974 50444641 707000>
                    );
                    3 =                     (
                        2,
                        <4578706f 72745044 46417070 00>
                    );
                    4 =                     (
                        2,
                        <50616765 73417070 00>
                    );
                    5 =                     (
                        2,
                        <52657669 65774170 7000>
                    );
                    6 =                     (
                        2,
                        <436f6d6d 656e7441 707000>
                    );
                    7 =                     (
                        2,
                        <46696c6c 5369676e 41707000>
                    );
                    8 =                     (
                        2,
                        <436f6c6c 65637453 69676e61 74757265 73417070 00>
                    );
                    9 =                     (
                        2,
                        <50617065 72546f50 44464170 7000>
                    );
                }
            );
            Featured =             (
                8,
                                {
                    ReviewApp =                     (
                        8,
                                                {
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            TimesOpened =                             (
                                10,
                                0
                            );
                        }
                    );
                    Version =                     (
                        10,
                        2
                    );
                }
            );
            Locale =             (
                4,
                <656e2d75 7300>
            );
            Registered =             (
                8,
                                {
                    0 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Create a PDF from any format"
                            );
                            ID =                             (
                                2,
                                <43726561 74655044 46417070 00>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "CreatePDF.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                "Create PDF"
                            );
                        }
                    );
                    1 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Edit text and images in a PDF file"
                            );
                            ID =                             (
                                2,
                                <45646974 50444641 707000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Edit.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                "Edit PDF"
                            );
                        }
                    );
                    10 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Share files for viewing or review and track responses"
                            );
                            ID =                             (
                                2,
                                <53656e64 41707046 756c6c00>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "TrackedSend.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                Share
                            );
                        }
                    );
                    11 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Combine multiple files into a single PDF"
                            );
                            ID =                             (
                                2,
                                <436f6d62 696e6541 707000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Combine.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                "Combine Files"
                            );
                        }
                    );
                    12 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Reduce PDF file size, enable fast web view, and control image and font options"
                            );
                            ID =                             (
                                2,
                                <4f707469 6d697a65 50444641 707000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "OptimizePDF.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                "Optimize PDF"
                            );
                        }
                    );
                    13 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Permanently delete sensitive text, graphics, or hidden data"
                            );
                            ID =                             (
                                2,
                                <52656461 63744170 7000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Redact.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                Redact
                            );
                        }
                    );
                    14 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Add stamps such as 'approved' or 'draft'"
                            );
                            ID =                             (
                                2,
                                <5374616d 70417070 00>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Stamp.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                Stamp
                            );
                        }
                    );
                    15 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Compare and highlight the differences between 2 files"
                            );
                            ID =                             (
                                2,
                                <436f6d70 61726541 707000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                2
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Compare.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                "Compare Files"
                            );
                        }
                    );
                    16 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Invite people to review a shared file and track responses"
                            );
                            ID =                             (
                                2,
                                <52657669 65774170 7000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Review.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                "Send for Review"
                            );
                        }
                    );
                    17 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Use guided actions to standardize routine PDF tasks"
                            );
                            ID =                             (
                                2,
                                <41637469 6f6e7341 707000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Actions.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                "Action Wizard"
                            );
                        }
                    );
                    18 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Create a customized collection of Acrobat features and share it with others"
                            );
                            ID =                             (
                                2,
                                <43726561 74654375 73746f6d 55494170 7000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "CreateCustom.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                "Create Custom Tool"
                            );
                        }
                    );
                    19 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Preview, preflight, correct, and prepare PDF files for high-end print production"
                            );
                            ID =                             (
                                2,
                                <5072696e 7450726f 64756374 696f6e41 707000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "PrintProduction.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                "Print Production"
                            );
                        }
                    );
                    2 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Convert a PDF to Microsoft Word, Excel, PowerPoint, and more"
                            );
                            ID =                             (
                                2,
                                <4578706f 72745044 46417070 00>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Export.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                "Export PDF"
                            );
                        }
                    );
                    20 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Create PDF/A, PDF/E, or PDF/X files to comply with ISO standards"
                            );
                            ID =                             (
                                2,
                                <5374616e 64617264 73417070 00>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Standards.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                "PDF Standards"
                            );
                        }
                    );
                    21 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Digitally sign or certify documents and validate authenticity"
                            );
                            ID =                             (
                                2,
                                <43657274 69666963 61746573 41707000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                1
                            );
                            Path =                             (
                                5,
                                "Certificates.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                Certificates
                            );
                        }
                    );
                    22 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Create and verify PDF files to meet accessibility standards for people with disabilities"
                            );
                            ID =                             (
                                2,
                                <41636365 73736962 696c6974 79417070 00>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Accessibility.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                Accessibility
                            );
                        }
                    );
                    23 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Add audio, video, and interactive elements"
                            );
                            ID =                             (
                                2,
                                <52696368 4d656469 61417070 00>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "RichMedia.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                "Add Rich Media"
                            );
                        }
                    );
                    24 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Enhance PDF forms and connect to databases with JavaScript"
                            );
                            ID =                             (
                                2,
                                <44657665 6c6f7065 72417070 00>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Developer.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                JavaScript
                            );
                        }
                    );
                    25 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Index PDF files to speed search across document collections"
                            );
                            ID =                             (
                                2,
                                <496e6465 78417070 00>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Index.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                Index
                            );
                        }
                    );
                    26 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Measure distance, area, and perimeter of objects"
                            );
                            ID =                             (
                                2,
                                <4d656173 75726541 707000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Measure.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                Measure
                            );
                        }
                    );
                    27 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                ""
                            );
                            ID =                             (
                                2,
                                <546f6f6c 7343656e 74657200>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "AppCenter.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                Tools
                            );
                        }
                    );
                    28 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                ""
                            );
                            ID =                             (
                                2,
                                <4156486f 6d6500>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Home.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                Home
                            );
                        }
                    );
                    29 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                ""
                            );
                            ID =                             (
                                2,
                                <56696577 657200>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Viewer.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                Viewer
                            );
                        }
                    );
                    3 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Add comments with highlights, sticky notes, and markup tools"
                            );
                            ID =                             (
                                2,
                                <436f6d6d 656e7441 707000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Comments.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                Comment
                            );
                        }
                    );
                    30 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                ""
                            );
                            ID =                             (
                                2,
                                <496e4170 70536967 6e696e67 41707000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "InAppSign.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                ""
                            );
                        }
                    );
                    31 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Home Welcome app for Acrobat Tour"
                            );
                            ID =                             (
                                2,
                                <486f6d65 57656c63 6f6d6541 707000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "HomeWelcome.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                "Home Welcome"
                            );
                        }
                    );
                    32 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                ""
                            );
                            ID =                             (
                                2,
                                <556e6966 69656453 68617265 41707000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "UnifiedShare.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                UnifiedShare
                            );
                        }
                    );
                    33 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Access more tools and enhanced functionalities"
                            );
                            ID =                             (
                                2,
                                <4d6f7265 546f6f6c 52485000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "MoreTools.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                "More Tools"
                            );
                        }
                    );
                    4 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Delete, insert, extract, or rotate pages"
                            );
                            ID =                             (
                                2,
                                <50616765 73417070 00>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Pages.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                "Organize Pages"
                            );
                        }
                    );
                    5 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Turn scans or photos of paper documents into searchable PDFs with selectable text"
                            );
                            ID =                             (
                                2,
                                <50617065 72546f50 44464170 7000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "PaperToPDF.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                "Enhance Scans"
                            );
                        }
                    );
                    6 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Prevent others from copying, printing, and editing the information in PDFs"
                            );
                            ID =                             (
                                2,
                                <50726f74 65637441 707000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Protect.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                Protect
                            );
                        }
                    );
                    7 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Fill and sign documents electronically"
                            );
                            ID =                             (
                                2,
                                <46696c6c 5369676e 41707000>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "FillSign.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                "Fill & Sign"
                            );
                        }
                    );
                    8 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Quickly convert Microsoft Word and Excel or scanned forms into PDF forms"
                            );
                            ID =                             (
                                2,
                                <466f726d 73417070 00>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "Forms.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                "Prepare Form"
                            );
                        }
                    );
                    9 =                     (
                        8,
                                                {
                            Description =                             (
                                5,
                                "Get documents signed electronically and track results"
                            );
                            ID =                             (
                                2,
                                <436f6c6c 65637453 69676e61 74757265 73417070 00>
                            );
                            InAppUpsellEnabled =                             (
                                0,
                                0
                            );
                            Inline =                             (
                                0,
                                0
                            );
                            Location =                             (
                                5,
                                install
                            );
                            MajorVersion =                             (
                                1,
                                1
                            );
                            MinorVersion =                             (
                                1,
                                0
                            );
                            Path =                             (
                                5,
                                "CollectSignatures.aapp"
                            );
                            ShowLabels =                             (
                                0,
                                0
                            );
                            Title =                             (
                                5,
                                "Adobe Sign"
                            );
                        }
                    );
                }
            );
        };
        Annots =         {
            Annots =             (
                8,
                                {
                    Annot =                     (
                        8,
                                                {
                            author =                             (
                                5,
                                calvin
                            );
                        }
                    );
                    "FreeText_003aFreeTextCallout" =                     (
                        8,
                                                {
                            strokeColor =                             (
                                8,
                                                                {
                                    0 =                                     (
                                        5,
                                        RGB
                                    );
                                    1 =                                     (
                                        3,
                                        "0.898040771484375"
                                    );
                                    2 =                                     (
                                        3,
                                        "0.133331298828125"
                                    );
                                    3 =                                     (
                                        3,
                                        "0.2156829833984375"
                                    );
                                }
                            );
                        }
                    );
                    "Highlight_003aHighlightNote" =                     (
                        8,
                                                {
                            opacity =                             (
                                3,
                                "0.4"
                            );
                            strokeColor =                             (
                                8,
                                                                {
                                    0 =                                     (
                                        5,
                                        RGB
                                    );
                                    1 =                                     (
                                        3,
                                        1
                                    );
                                    2 =                                     (
                                        3,
                                        "0.819610595703125"
                                    );
                                    3 =                                     (
                                        3,
                                        0
                                    );
                                }
                            );
                        }
                    );
                    "Line_003aLineArrow" =                     (
                        8,
                                                {
                            strokeColor =                             (
                                8,
                                                                {
                                    0 =                                     (
                                        5,
                                        RGB
                                    );
                                    1 =                                     (
                                        3,
                                        "0.898040771484375"
                                    );
                                    2 =                                     (
                                        3,
                                        "0.133331298828125"
                                    );
                                    3 =                                     (
                                        3,
                                        "0.2156829833984375"
                                    );
                                }
                            );
                        }
                    );
                }
            );
            StampsPaletteInvisible =             (
                0,
                1
            );
        };
        Collab =         {
            ServerSettings =             (
                8,
                                {
                }
            );
        };
        EFSPlugin =         {
            EFSPauseState =             (
                1,
                0
            );
        };
        EULAAcceptedForBrowser = 1;
        FTEDialog =         {
            ShowInstallFTE =             (
                0,
                1
            );
        };
        FlashDebug =         {
            AutomationEnabled =             (
                0,
                0
            );
        };
        HomeWelcome =         {
            AppVersion =             (
                4,
                <32343139 313000>
            );
            IsAcrobatUpdated =             (
                0,
                0
            );
            KillSwitchCheckDay =             (
                1,
                20190426
            );
            KillSwitchOn =             (
                0,
                0
            );
        };
        IPM =         {
            pairID =             (
                0,
                0
            );
        };
        OnBoardingSection =         {
            appVersion =             (
                4,
                <32343139 313000>
            );
            homeView =             (
                8,
                                {
                    BannerContent =                     (
                        4,
                        <576f726b 206f6e20 74686520 676f2077 69746820 74686520 41646f62 65204163 726f6261 74205265 61646572 20617070 2e20416e 6e6f7461 74652c20 7369676e 2c20616e 64207368 61726520 50444673 206f6e20 796f7572 2070686f 6e652c20 616e6420 65646974 206f6e20 7461626c 6574732e 00>
                    );
                    BannerTitle =                     (
                        4,
                        <47657420 41707000>
                    );
                    CardContent =                     (
                        4,
                        <4163726f 6261744d 6f62696c 65436172 6400>
                    );
                    CardTitle =                     (
                        4,
                        <4d6f6269 6c654163 726f6261 74436172 6400>
                    );
                    CardType =                     (
                        4,
                        <4c61756e 63684654 45436172 6400>
                    );
                    Offset =                     (
                        4,
                        <34333830 3000>
                    );
                    "first_display" =                     (
                        1,
                        432281
                    );
                }
            );
            homeViewVersion =             (
                1,
                0
            );
            locale =             (
                4,
                <656e2d75 7300>
            );
        };
        Originals =         {
            ProofingSpace =             (
                4,
                <552e532e 20576562 20436f61 74656420 2853574f 50292076 3200>
            );
        };
        PaperCapturePlugin =         {
            Settings =             (
                8,
                                {
                    Downsample =                     (
                        1,
                        "-1"
                    );
                    Format =                     (
                        1,
                        0
                    );
                    IgnoreRenderableText =                     (
                        0,
                        0
                    );
                    Language =                     (
                        1,
                        "-1"
                    );
                    ThrowRenderableTextError =                     (
                        0,
                        1
                    );
                }
            );
        };
        PrefsDialog =         {
            LastPrefsPanel =             (
                2,
                <44697370 6c617900>
            );
        };
        SDI =         {
            MaximizeNextDocument =             (
                0,
                0
            );
            NullDocBottom =             (
                1,
                820
            );
            NullDocLeft =             (
                1,
                0
            );
            NullDocMaximized =             (
                0,
                0
            );
            NullDocRight =             (
                1,
                1440
            );
            NullDocTop =             (
                1,
                23
            );
        };
        Security =         {
            PPKLite =             (
                8,
                                {
                    "SP_Favorites" =                     (
                        8,
                                                {
                            0 =                             (
                                8,
                                                                {
                                    Handler =                                     (
                                        2,
                                        <41646f62 652e5075 62536563 00>
                                    );
                                    Id =                                     (
                                        4,
                                        <53505f50 4b495f64 65666175 6c7400>
                                    );
                                    IsFavorite =                                     (
                                        0,
                                        1
                                    );
                                    Name =                                     (
                                        5,
                                        "Encrypt with Certificate"
                                    );
                                }
                            );
                            1 =                             (
                                8,
                                                                {
                                    Handler =                                     (
                                        2,
                                        <5374616e 64617264 00>
                                    );
                                    Id =                                     (
                                        4,
                                        <53505f53 54445f64 65666175 6c7400>
                                    );
                                    IsFavorite =                                     (
                                        0,
                                        1
                                    );
                                    Name =                                     (
                                        5,
                                        "Encrypt with Password"
                                    );
                                }
                            );
                        }
                    );
                }
            );
        };
        Selection =         {
            DefaultSelect =             (
                2,
                <53656c65 637400>
            );
        };
        ShowSplashScreen = 0;
        ToolsSearch =         {
            Locale =             (
                4,
                <656e2d75 7300>
            );
            RegisteredApps =             (
                8,
                                {
                    0 =                     (
                        8,
                                                {
                            AppID =                             (
                                2,
                                <45787465 6e645365 61726368 56697274 75616c41 707000>
                            );
                        }
                    );
                }
            );
            UpdateId =             (
                1,
                0
            );
            VersionHi =             (
                10,
                319442563
            );
            VersionLo =             (
                10,
                322322
            );
        };
        Updater =         {
            FirstTimeAppHasRun =             (
                0,
                0
            );
        };
        Workflow =         {
            Locale =             (
                4,
                <656e2d75 7300>
            );
            Registered =             (
                8,
                                {
                    0 =                     (
                        8,
                                                {
                            BaseFolderName =                             (
                                5,
                                install
                            );
                            Description =                             (
                                5,
                                "Make your PDF accessible to a broader audience using Acrobat accessibility tools. These steps will ensure that scanned text, content structure and document information are available for assistive technology."
                            );
                            FileFormat =                             (
                                5,
                                11
                            );
                            ID =                             (
                                2,
                                <37453743 32393939 44343935 41373639 34374530 38353031 45304146 46463700>
                            );
                            RelativeDIPath =                             (
                                5,
                                "Action01.sequ"
                            );
                            ShowStartDialog =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                "Make Accessible"
                            );
                        }
                    );
                    1 =                     (
                        8,
                                                {
                            BaseFolderName =                             (
                                5,
                                install
                            );
                            Description =                             (
                                5,
                                "Be sure hidden information is removed and documents are branded with appropriate watermarks, headers, or footers before distributing."
                            );
                            FileFormat =                             (
                                5,
                                11
                            );
                            ID =                             (
                                2,
                                <46344536 36444242 46333839 34363333 36423444 41423235 32413134 37434200>
                            );
                            RelativeDIPath =                             (
                                5,
                                "Action06.sequ"
                            );
                            ShowStartDialog =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                "Prepare for Distribution"
                            );
                        }
                    );
                    2 =                     (
                        8,
                                                {
                            BaseFolderName =                             (
                                5,
                                install
                            );
                            Description =                             (
                                5,
                                "Compress images, optimize image colors, embed fonts, and enable fast web view."
                            );
                            FileFormat =                             (
                                5,
                                11
                            );
                            ID =                             (
                                2,
                                <39353333 39373443 34424332 46443736 35433642 33353633 32314336 38444500>
                            );
                            RelativeDIPath =                             (
                                5,
                                "Action04.sequ"
                            );
                            ShowStartDialog =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                "Optimize for Web and Mobile"
                            );
                        }
                    );
                    3 =                     (
                        8,
                                                {
                            BaseFolderName =                             (
                                5,
                                install
                            );
                            Description =                             (
                                5,
                                "Make scanned documents more useful by converting their contents into searchable text, correcting page orientation, and reducing file size."
                            );
                            FileFormat =                             (
                                5,
                                11
                            );
                            ID =                             (
                                2,
                                <36393943 32373236 45374638 39393034 45424234 44344245 46463644 32354300>
                            );
                            RelativeDIPath =                             (
                                5,
                                "Action05.sequ"
                            );
                            ShowStartDialog =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                "Optimize Scanned Documents"
                            );
                        }
                    );
                    4 =                     (
                        8,
                                                {
                            BaseFolderName =                             (
                                5,
                                install
                            );
                            Description =                             (
                                5,
                                "Prepare documents that conform to PDF/A archive standards for reliable viewing and printing over a long period of time."
                            );
                            FileFormat =                             (
                                5,
                                11
                            );
                            ID =                             (
                                2,
                                <38453633 34443639 30394138 38444534 38313636 33393942 30364443 37413800>
                            );
                            RelativeDIPath =                             (
                                5,
                                "Action02.sequ"
                            );
                            ShowStartDialog =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                "Archive Documents"
                            );
                        }
                    );
                    5 =                     (
                        8,
                                                {
                            BaseFolderName =                             (
                                5,
                                install
                            );
                            Description =                             (
                                5,
                                "Redact sensitive content, remove hidden information and add password protection if needed."
                            );
                            FileFormat =                             (
                                5,
                                11
                            );
                            ID =                             (
                                2,
                                <30373931 39413738 31334441 37444642 42343133 35413131 37463643 37424500>
                            );
                            RelativeDIPath =                             (
                                5,
                                "Action03.sequ"
                            );
                            ShowStartDialog =                             (
                                0,
                                1
                            );
                            Title =                             (
                                5,
                                "Publish Sensitive Information"
                            );
                        }
                    );
                }
            );
        };
        Workflows =         {
            Services =             (
                8,
                                {
                    ScanAppKillSwitch =                     (
                        8,
                                                {
                            KillSwitchOn =                             (
                                0,
                                0
                            );
                        }
                    );
                }
            );
        };
        multimedia =         {
            ColorAndBorder =             (
                8,
                                {
                    BorderColor =                     (
                        6,
                        <01000000 00000000 00000000 00000000 00000000>
                    );
                    BorderStyle =                     (
                        6,
                        <00000000 00000000 01000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000>
                    );
                }
            );
        };
    };
    NSCGSIsSynchronous = 1;
    NSCGSIsSynchronousM6 = 1;
    NSCGSIsSynchronousM7 = 1;
    NSWindowDisplayWithRunLoopObserver = 1;
}
